import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppShell } from '@/components/layout/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { useUpdatePost, useUploadImage, useGenerateCaption } from '@/hooks/use-api';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { toast } from '@/hooks/use-toast';
import { Upload, X, Sparkles, Loader2, Image as ImageIcon } from 'lucide-react';

export default function PostNew() {
  return (
    <AuthGate>
      <PostNewContent />
    </AuthGate>
  );
}

function PostNewContent() {
  const navigate = useNavigate();
  const uploadImage = useUploadImage();
  const generateCaption = useGenerateCaption();
  const updatePost = useUpdatePost();

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [images, setImages] = useState<string[]>([]);
  const [uploading, setUploading] = useState(false);
  const [publishing, setPublishing] = useState(false);

  const handleImageUpload = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'image/jpeg,image/png,image/webp,image/gif';
    input.multiple = true;
    input.onchange = async () => {
      const files = Array.from(input.files ?? []);
      if (images.length + files.length > 10) {
        toast({ title: 'Maximum 10 images', variant: 'destructive' });
        return;
      }
      setUploading(true);
      for (const file of files) {
        if (file.size > 5 * 1024 * 1024) {
          toast({ title: `${file.name} is too large (max 5MB)`, variant: 'destructive' });
          continue;
        }
        try {
          const result = await uploadImage.mutateAsync(file);
          setImages((prev) => [...prev, (result as any).url]);
        } catch {
          toast({ title: `Failed to upload ${file.name}`, variant: 'destructive' });
        }
      }
      setUploading(false);
    };
    input.click();
  };

  const removeImage = (index: number) => {
    setImages((prev) => prev.filter((_, i) => i !== index));
  };

  const handleGenerateCaption = () => {
    generateCaption.mutate(
      { stats: {}, imageUrls: images },
      {
        onSuccess: (data) => {
          if (data.title) setTitle(data.title);
          if (data.description) setDescription(data.description);
          toast({ title: `Caption generated by ${data.generated_by}` });
        },
        onError: () => toast({ title: 'Failed to generate caption', variant: 'destructive' }),
      }
    );
  };

  const handlePublish = async () => {
    if (!title.trim()) {
      toast({ title: 'Title is required', variant: 'destructive' });
      return;
    }
    setPublishing(true);
    try {
      await updatePost.mutateAsync({
        id: 'new',
        title: title.trim(),
        description: description.trim() || undefined,
        images: images.length > 0 ? images : undefined,
        is_published: true,
      });
      toast({ title: 'Post published!' });
      navigate('/feed');
    } catch {
      toast({ title: 'Failed to publish post', variant: 'destructive' });
    }
    setPublishing(false);
  };

  return (
    <AppShell>
      <div className="max-w-2xl mx-auto space-y-6">
        <h1 className="text-2xl font-bold text-foreground">New Post</h1>

        {/* Title */}
        <div className="space-y-2">
          <Label>Title</Label>
          <Input
            value={title}
            onChange={(e) => setTitle(e.target.value.slice(0, 100))}
            placeholder="What did you build today?"
            className="bg-muted/50"
          />
          <p className="text-xs text-muted-foreground text-right">{title.length}/100</p>
        </div>

        {/* Description */}
        <div className="space-y-2">
          <Label>Description</Label>
          <Textarea
            value={description}
            onChange={(e) => setDescription(e.target.value.slice(0, 500))}
            placeholder="Tell the story of your session..."
            className="min-h-[120px] resize-none bg-muted/50"
          />
          <p className="text-xs text-muted-foreground text-right">{description.length}/500</p>
        </div>

        {/* AI Caption */}
        <Button
          variant="outline"
          size="sm"
          onClick={handleGenerateCaption}
          disabled={generateCaption.isPending}
        >
          {generateCaption.isPending ? (
            <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4 mr-1.5" />
          )}
          Generate caption with AI
        </Button>

        {/* Images */}
        <div className="space-y-3">
          <Label>Screenshots (optional)</Label>
          {images.length > 0 && (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {images.map((url, i) => (
                <div key={i} className="relative group aspect-video rounded-md overflow-hidden border border-border">
                  <img src={url} alt={`Upload ${i + 1}`} className="w-full h-full object-cover" />
                  <button
                    onClick={() => removeImage(i)}
                    className="absolute top-1 right-1 rounded-full bg-black/60 p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="h-3 w-3 text-white" />
                  </button>
                </div>
              ))}
            </div>
          )}
          {images.length < 10 && (
            <button
              onClick={handleImageUpload}
              disabled={uploading}
              className="flex items-center gap-2 rounded-lg border-2 border-dashed border-border bg-muted/20 px-4 py-3 text-sm text-muted-foreground hover:border-muted-foreground hover:text-foreground transition-colors w-full justify-center"
            >
              {uploading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <ImageIcon className="h-4 w-4" />
              )}
              {uploading ? 'Uploading...' : `Add images (${images.length}/10)`}
            </button>
          )}
        </div>

        {/* CLI hint */}
        <div className="rounded-lg border border-border bg-muted/30 p-4">
          <p className="text-sm text-muted-foreground">
            <strong className="text-foreground">Tip:</strong> Use the CLI to auto-import your session data:
          </p>
          <code className="block mt-2 text-xs font-mono text-foreground bg-muted/50 rounded px-3 py-2">
            npx awarts@latest push --days 1
          </code>
        </div>

        {/* Actions */}
        <div className="flex gap-3 pt-2">
          <Button variant="outline" onClick={() => navigate(-1)}>
            Cancel
          </Button>
          <Button onClick={handlePublish} disabled={publishing || !title.trim()} className="flex-1">
            {publishing ? 'Publishing...' : 'Publish Post'}
          </Button>
        </div>
      </div>
    </AppShell>
  );
}
