import { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { AppShell } from '@/components/layout/AppShell';
import { ActivityCard } from '@/components/ActivityCard';
import { CommentThread } from '@/components/CommentThread';
import { SkeletonCard } from '@/components/SkeletonCard';
import { ErrorState } from '@/components/ErrorState';
import { ProviderPieChart } from '@/components/charts/ProviderPieChart';
import { TokenBarChart } from '@/components/charts/TokenBarChart';
import { usePost, useComments, useUpdatePost, useGenerateCaption } from '@/hooks/use-api';
import { useAuth } from '@/context/AuthContext';
import { transformFeedPost, transformComment } from '@/lib/transformers';
import { formatCost, formatTokens } from '@/lib/format';
import { PROVIDERS } from '@/lib/constants';
import { ArrowLeft, Pencil, X, Sparkles, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { SEO } from '@/components/SEO';
import { toast } from '@/hooks/use-toast';

export default function PostDetail() {
  const navigate = useNavigate();
  const { id } = useParams<{ id: string }>();
  const { user } = useAuth();
  const { data: rawPost, isLoading, error } = usePost(id ?? '');
  const isError = !!error;
  const { data: commentsData } = useComments(id ?? '');
  const updatePost = useUpdatePost();
  const generateCaption = useGenerateCaption();

  const post = rawPost ? transformFeedPost(rawPost) : null;
  const comments = commentsData?.pages.flatMap(
    (page) => page.comments.map(transformComment)
  ) ?? [];

  const isOwner = !!(user && post && user.username === post.user.username);

  // Inline edit state
  const [editing, setEditing] = useState(false);
  const [editTitle, setEditTitle] = useState('');
  const [editDescription, setEditDescription] = useState('');
  const [saving, setSaving] = useState(false);

  const startEditing = () => {
    if (!post) return;
    setEditTitle(post.title || '');
    setEditDescription(post.description || '');
    setEditing(true);
  };

  const cancelEditing = () => {
    setEditing(false);
  };

  const handleSave = async () => {
    if (!post) return;
    setSaving(true);
    try {
      await updatePost.mutateAsync({
        id: post.id,
        title: editTitle.trim() || undefined,
        description: editDescription.trim() || undefined,
      });
      toast({ title: 'Post updated!' });
      setEditing(false);
    } catch {
      toast({ title: 'Failed to update post', variant: 'destructive' });
    }
    setSaving(false);
  };

  const handleGenerateCaption = async () => {
    if (!post) return;
    try {
      const result = await generateCaption.mutateAsync({
        stats: {
          totalCost: post.stats.cost ?? 0,
          totalTokens: (post.stats.inputTokens ?? 0) + (post.stats.outputTokens ?? 0),
          providers: post.providers ?? [],
          date: post.createdAt?.slice(0, 10) ?? new Date().toISOString().slice(0, 10),
        },
        preferredProvider: post.providers?.[0],
      });
      if (result.title) setEditTitle(result.title);
      if (result.description) setEditDescription(result.description);
      toast({ title: `Caption generated by ${result.generated_by}` });
    } catch {
      toast({ title: 'Failed to generate caption', variant: 'destructive' });
    }
  };

  if (isLoading) {
    return (
      <AppShell>
        <div className="max-w-2xl mx-auto space-y-6">
          <SkeletonCard />
        </div>
      </AppShell>
    );
  }

  if (isError || !post) {
    return (
      <AppShell>
        <div className="max-w-2xl mx-auto">
          <ErrorState message="Post not found." onRetry={() => window.location.reload()} />
        </div>
      </AppShell>
    );
  }

  // Build chart data from provider breakdown
  const pieData = post.providerBreakdown.map((pb) => ({
    provider: pb.provider,
    cost: pb.cost,
    inputTokens: pb.inputTokens,
    outputTokens: pb.outputTokens,
    days: 1,
  }));

  // Token bar data — single bar per provider for this post
  const tokenData = post.providerBreakdown.map((pb) => ({
    date: PROVIDERS[pb.provider]?.name ?? pb.provider,
    input: pb.inputTokens,
    output: pb.outputTokens,
  }));

  return (
    <AppShell>
      <SEO title={post.title || 'Session Detail'} description={post.description || `AI coding session by @${post.user?.username ?? 'unknown'} on AWARTS.`} canonical={`/post/${id}`} />
      <div className="max-w-2xl mx-auto space-y-6">
        <Button variant="ghost" size="sm" onClick={() => navigate(-1)} className="mb-2">
          <ArrowLeft className="h-4 w-4 mr-1.5" /> Back
        </Button>

        <ActivityCard post={post} />

        {/* Inline edit for post owner */}
        {isOwner && (
          <div className="rounded-lg border border-border bg-card p-5">
            {editing ? (
              <div className="space-y-4">
                <h3 className="text-sm font-semibold text-foreground">Edit Post</h3>
                <div className="space-y-2">
                  <Input
                    value={editTitle}
                    onChange={(e) => setEditTitle(e.target.value.slice(0, 100))}
                    placeholder="What did you build today?"
                    className="bg-muted/50"
                  />
                  <p className="text-xs text-muted-foreground text-right">{editTitle.length}/100</p>
                </div>
                <div className="space-y-2">
                  <Textarea
                    value={editDescription}
                    onChange={(e) => setEditDescription(e.target.value.slice(0, 500))}
                    placeholder="Tell the story of your session..."
                    className="min-h-[100px] resize-none bg-muted/50"
                  />
                  <p className="text-xs text-muted-foreground text-right">{editDescription.length}/500</p>
                </div>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleGenerateCaption}
                    disabled={generateCaption.isPending}
                  >
                    {generateCaption.isPending ? (
                      <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
                    ) : (
                      <Sparkles className="h-4 w-4 mr-1.5" />
                    )}
                    AI Caption
                  </Button>
                  <div className="ml-auto flex gap-2">
                    <Button variant="ghost" size="sm" onClick={cancelEditing}>
                      Cancel
                    </Button>
                    <Button size="sm" onClick={handleSave} disabled={saving}>
                      {saving ? 'Saving...' : 'Save'}
                    </Button>
                  </div>
                </div>
              </div>
            ) : (
              <button
                onClick={startEditing}
                className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors w-full"
              >
                <Pencil className="h-4 w-4" />
                Edit title & description
              </button>
            )}
          </div>
        )}

        {/* Usage breakdown */}
        {post.providerBreakdown.length > 0 && (
          <div className="rounded-lg border border-border bg-card p-5 space-y-5">
            <h3 className="text-sm font-semibold text-foreground">Usage Breakdown</h3>

            {/* Charts side by side on larger screens */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
              {pieData.length > 0 && (
                <div>
                  <p className="text-xs text-muted-foreground mb-3">Cost by Provider</p>
                  <ProviderPieChart data={pieData} />
                </div>
              )}
              {tokenData.length > 0 && (
                <div>
                  <p className="text-xs text-muted-foreground mb-3">Token Usage</p>
                  <TokenBarChart data={tokenData} />
                </div>
              )}
            </div>

            {/* Per-provider detail rows */}
            <div className="space-y-2">
              {post.providerBreakdown.map((pb) => (
                <div key={pb.provider} className="flex items-center justify-between rounded-md bg-muted/30 px-4 py-2.5">
                  <div className="flex items-center gap-2">
                    <span
                      className="inline-block h-2.5 w-2.5 rounded-full"
                      style={{ backgroundColor: PROVIDERS[pb.provider]?.color }}
                    />
                    <span className="text-sm font-medium text-foreground">
                      {PROVIDERS[pb.provider]?.name ?? pb.provider}
                    </span>
                  </div>
                  <div className="flex items-center gap-4 text-xs font-mono text-muted-foreground">
                    <span title="Cost">{formatCost(pb.cost)}</span>
                    <span title="Input tokens">{formatTokens(pb.inputTokens)} in</span>
                    <span title="Output tokens">{formatTokens(pb.outputTokens)} out</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Comments */}
        <div className="rounded-lg border border-border bg-card p-5">
          <h3 className="text-sm font-semibold text-foreground mb-4">
            Comments {post.commentCount > 0 && `(${post.commentCount})`}
          </h3>
          <CommentThread postId={post.id} comments={comments} />
        </div>
      </div>
    </AppShell>
  );
}
