import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AppShell } from '@/components/layout/AppShell';
import { AuthGate } from '@/components/AuthGate';
import { useUserPosts, useUpdatePost, useUploadImage, useGenerateCaption } from '@/hooks/use-api';
import { useAuth } from '@/context/AuthContext';
import { transformFeedPost } from '@/lib/transformers';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { toast } from '@/hooks/use-toast';
import { Upload, X, Sparkles, Loader2, Image as ImageIcon, Terminal, ChevronRight } from 'lucide-react';
import { formatDate, formatCost } from '@/lib/format';
import { Link } from 'react-router-dom';
import { SEO } from '@/components/SEO';

export default function PostNew() {
  return (
    <AuthGate>
      <PostNewContent />
    </AuthGate>
  );
}

function PostNewContent() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const uploadImage = useUploadImage();
  const generateCaption = useGenerateCaption();
  const updatePost = useUpdatePost();
  const { data: postsData, isLoading: postsLoading } = useUserPosts(user?.username ?? '');

  const [selectedPostId, setSelectedPostId] = useState<string | null>(null);
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [images, setImages] = useState<string[]>([]);
  const [uploading, setUploading] = useState(false);
  const [publishing, setPublishing] = useState(false);

  const posts = postsData?.pages.flatMap((page) => page.posts.map(transformFeedPost)) ?? [];

  // Select a post to edit
  const handleSelectPost = (post: any) => {
    setSelectedPostId(post.id);
    setTitle(post.title || '');
    setDescription(post.description || '');
    setImages(post.images || []);
  };

  const handleImageUpload = () => {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = 'image/jpeg,image/png,image/webp,image/gif';
    input.multiple = true;
    input.onchange = async () => {
      const files = Array.from(input.files ?? []);
      if (images.length + files.length > 10) {
        toast({ title: 'Maximum 10 images', variant: 'destructive' });
        return;
      }
      setUploading(true);
      for (const file of files) {
        if (file.size > 5 * 1024 * 1024) {
          toast({ title: `${file.name} is too large (max 5MB)`, variant: 'destructive' });
          continue;
        }
        try {
          const result = await uploadImage.mutateAsync(file);
          setImages((prev) => [...prev, (result as any).url]);
        } catch {
          toast({ title: `Failed to upload ${file.name}`, variant: 'destructive' });
        }
      }
      setUploading(false);
    };
    input.click();
  };

  const removeImage = (index: number) => {
    setImages((prev) => prev.filter((_, i) => i !== index));
  };

  const handleGenerateCaption = async () => {
    const selectedPost = posts.find((p) => p.id === selectedPostId);
    try {
      const result = await generateCaption.mutateAsync({
        stats: {
          totalCost: selectedPost?.stats.cost ?? 0,
          totalTokens: (selectedPost?.stats.inputTokens ?? 0) + (selectedPost?.stats.outputTokens ?? 0),
          providers: selectedPost?.providers ?? [],
          date: selectedPost?.createdAt?.slice(0, 10) ?? new Date().toISOString().slice(0, 10),
        },
        preferredProvider: selectedPost?.providers?.[0],
      });
      if (result.title) setTitle(result.title);
      if (result.description) setDescription(result.description);
      toast({ title: `Caption generated by ${result.generated_by}` });
    } catch {
      toast({ title: 'Failed to generate caption', variant: 'destructive' });
    }
  };

  const handlePublish = async () => {
    if (!selectedPostId) {
      toast({ title: 'Please select a session to edit', variant: 'destructive' });
      return;
    }
    if (!title.trim()) {
      toast({ title: 'Title is required', variant: 'destructive' });
      return;
    }
    setPublishing(true);
    try {
      await updatePost.mutateAsync({
        id: selectedPostId,
        title: title.trim(),
        description: description.trim() || undefined,
        images: images.length > 0 ? images : undefined,
        is_published: true,
      });
      toast({ title: 'Post updated!' });
      navigate(`/post/${selectedPostId}`);
    } catch {
      toast({ title: 'Failed to update post', variant: 'destructive' });
    }
    setPublishing(false);
  };

  // If no post is selected, show the session picker
  if (!selectedPostId) {
    return (
      <AppShell>
        <SEO title="Edit Post" description="Add a title, description, and screenshots to your AI coding session on AWARTS." noindex />
        <div className="max-w-2xl mx-auto space-y-6">
          <h1 className="text-2xl font-bold text-foreground">Edit a Session Post</h1>
          <p className="text-sm text-muted-foreground">
            Select a session to add a title, description, and screenshots. Sessions are auto-created when you push data from the CLI.
          </p>

          {/* CLI hint */}
          <div className="rounded-lg border border-border bg-muted/30 p-4">
            <div className="flex items-start gap-3">
              <Terminal className="h-5 w-5 text-primary mt-0.5" />
              <div>
                <p className="text-sm font-medium text-foreground">Push your sessions first</p>
                <p className="text-sm text-muted-foreground mt-1">
                  Run the CLI to auto-import your AI coding sessions:
                </p>
                <code className="block mt-2 text-xs font-mono text-foreground bg-muted/50 rounded px-3 py-2">
                  npx awarts@latest sync
                </code>
              </div>
            </div>
          </div>

          {/* Recent sessions */}
          {postsLoading ? (
            <div className="space-y-3">
              {[...Array(3)].map((_, i) => (
                <div key={i} className="h-16 rounded-lg border border-border bg-card animate-pulse" />
              ))}
            </div>
          ) : posts.length === 0 ? (
            <div className="text-center py-12 text-muted-foreground">
              <p className="text-lg font-medium">No sessions yet</p>
              <p className="text-sm mt-1">Push some data with the CLI first, then come back to add details.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {posts.map((post) => (
                <button
                  key={post.id}
                  onClick={() => handleSelectPost(post)}
                  className="w-full flex items-center justify-between rounded-lg border border-border bg-card p-4 text-left hover:border-primary/50 hover:bg-muted/30 transition-colors"
                >
                  <div>
                    <p className="font-medium text-foreground">
                      {post.title || `Session on ${formatDate(post.createdAt)}`}
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      {post.providers.join(', ')} &middot; {formatCost(post.stats.cost)} &middot; {formatDate(post.createdAt)}
                    </p>
                  </div>
                  <ChevronRight className="h-4 w-4 text-muted-foreground" />
                </button>
              ))}
            </div>
          )}
        </div>
      </AppShell>
    );
  }

  // Post editing form
  return (
    <AppShell>
      <div className="max-w-2xl mx-auto space-y-6">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={() => setSelectedPostId(null)}>
            Back
          </Button>
          <h1 className="text-2xl font-bold text-foreground">Edit Post</h1>
        </div>

        {/* Title */}
        <div className="space-y-2">
          <Label>Title</Label>
          <Input
            value={title}
            onChange={(e) => setTitle(e.target.value.slice(0, 100))}
            placeholder="What did you build today?"
            className="bg-muted/50"
          />
          <p className="text-xs text-muted-foreground text-right">{title.length}/100</p>
        </div>

        {/* Description */}
        <div className="space-y-2">
          <Label>Description</Label>
          <Textarea
            value={description}
            onChange={(e) => setDescription(e.target.value.slice(0, 500))}
            placeholder="Tell the story of your session..."
            className="min-h-[120px] resize-none bg-muted/50"
          />
          <p className="text-xs text-muted-foreground text-right">{description.length}/500</p>
        </div>

        {/* AI Caption */}
        <Button
          variant="outline"
          size="sm"
          onClick={handleGenerateCaption}
          disabled={generateCaption.isPending}
        >
          {generateCaption.isPending ? (
            <Loader2 className="h-4 w-4 mr-1.5 animate-spin" />
          ) : (
            <Sparkles className="h-4 w-4 mr-1.5" />
          )}
          Generate caption with AI
        </Button>

        {/* Images */}
        <div className="space-y-3">
          <Label>Screenshots (optional)</Label>
          {images.length > 0 && (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {images.map((url, i) => (
                <div key={i} className="relative group aspect-video rounded-md overflow-hidden border border-border">
                  <img src={url} alt={`Upload ${i + 1}`} className="w-full h-full object-cover" />
                  <button
                    onClick={() => removeImage(i)}
                    className="absolute top-1 right-1 rounded-full bg-black/60 p-1 opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="h-3 w-3 text-white" />
                  </button>
                </div>
              ))}
            </div>
          )}
          {images.length < 10 && (
            <button
              onClick={handleImageUpload}
              disabled={uploading}
              className="flex items-center gap-2 rounded-lg border-2 border-dashed border-border bg-muted/20 px-4 py-3 text-sm text-muted-foreground hover:border-muted-foreground hover:text-foreground transition-colors w-full justify-center"
            >
              {uploading ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <ImageIcon className="h-4 w-4" />
              )}
              {uploading ? 'Uploading...' : `Add images (${images.length}/10)`}
            </button>
          )}
        </div>

        {/* Actions */}
        <div className="flex gap-3 pt-2">
          <Button variant="outline" onClick={() => setSelectedPostId(null)}>
            Cancel
          </Button>
          <Button onClick={handlePublish} disabled={publishing || !title.trim()} className="flex-1">
            {publishing ? 'Saving...' : 'Save Post'}
          </Button>
        </div>
      </div>
    </AppShell>
  );
}
