-- AWARTS Countries to Regions seed data
INSERT INTO countries_to_regions (country_code, country_name, region) VALUES
  ('US', 'United States', 'north-america'),
  ('CA', 'Canada', 'north-america'),
  ('MX', 'Mexico', 'latin-america'),
  ('GB', 'United Kingdom', 'europe'),
  ('DE', 'Germany', 'europe'),
  ('FR', 'France', 'europe'),
  ('NL', 'Netherlands', 'europe'),
  ('SE', 'Sweden', 'europe'),
  ('PL', 'Poland', 'europe'),
  ('ES', 'Spain', 'europe'),
  ('IT', 'Italy', 'europe'),
  ('PT', 'Portugal', 'europe'),
  ('CH', 'Switzerland', 'europe'),
  ('AT', 'Austria', 'europe'),
  ('BE', 'Belgium', 'europe'),
  ('NO', 'Norway', 'europe'),
  ('DK', 'Denmark', 'europe'),
  ('FI', 'Finland', 'europe'),
  ('IE', 'Ireland', 'europe'),
  ('CZ', 'Czech Republic', 'europe'),
  ('RO', 'Romania', 'europe'),
  ('HU', 'Hungary', 'europe'),
  ('UA', 'Ukraine', 'europe'),
  ('GR', 'Greece', 'europe'),
  ('IN', 'India', 'asia'),
  ('CN', 'China', 'asia'),
  ('JP', 'Japan', 'asia'),
  ('KR', 'South Korea', 'asia'),
  ('SG', 'Singapore', 'asia'),
  ('TW', 'Taiwan', 'asia'),
  ('HK', 'Hong Kong', 'asia'),
  ('TH', 'Thailand', 'asia'),
  ('VN', 'Vietnam', 'asia'),
  ('PH', 'Philippines', 'asia'),
  ('MY', 'Malaysia', 'asia'),
  ('ID', 'Indonesia', 'asia'),
  ('PK', 'Pakistan', 'asia'),
  ('BD', 'Bangladesh', 'asia'),
  ('LK', 'Sri Lanka', 'asia'),
  ('AU', 'Australia', 'oceania'),
  ('NZ', 'New Zealand', 'oceania'),
  ('BR', 'Brazil', 'latin-america'),
  ('AR', 'Argentina', 'latin-america'),
  ('CL', 'Chile', 'latin-america'),
  ('CO', 'Colombia', 'latin-america'),
  ('PE', 'Peru', 'latin-america'),
  ('UY', 'Uruguay', 'latin-america'),
  ('NG', 'Nigeria', 'africa'),
  ('ZA', 'South Africa', 'africa'),
  ('EG', 'Egypt', 'africa'),
  ('KE', 'Kenya', 'africa'),
  ('GH', 'Ghana', 'africa'),
  ('MA', 'Morocco', 'africa'),
  ('TN', 'Tunisia', 'africa'),
  ('ET', 'Ethiopia', 'africa'),
  ('IL', 'Israel', 'asia'),
  ('AE', 'United Arab Emirates', 'asia'),
  ('SA', 'Saudi Arabia', 'asia'),
  ('TR', 'Turkey', 'europe'),
  ('RU', 'Russia', 'europe')
ON CONFLICT (country_code) DO NOTHING;
